### ISSUE TITLE
Enable a debugMode switch

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/psbuild#15]
After building the project it would be nice if we could inspect the resulting project file. To facilitate this let's add a `-debugMode` switch to `Invoke-MSBuild` that will use the MSBuild APIs to invoke the build and then return the build result as well as resulting `ProjectInstance`.

Since we will be calling the APIs instead of the command line we may not be able to understand all the properties but known ones should be passed in.
#### Tasks
- [x] Add -debugMode switch
- [x] Pass in properties during build
- [x] Pass in targets during build
- [ ] Attach console logger
- [ ] Attach file loggers
- [ ] Pass in max node count
- [ ] Ability to set toolsversion
- [x] Create a parameter set on Invoke-MSBuild
- [x] Create helper functions (Eval-Property/Eval-Item/Expand-String) that act on the last build result
- [x] Add evaluation functions to simplify
- [x] Eval-Property
- [x] Eval-Item
- [x] Eval-String
